name: frontend
on: [push, pull_request]
jobs:
  build:
    name: Check format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./frontend/bike-data-app
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: check format
        working-directory: ./frontend/bike-data-app
        run: |
          yarn format:check
      - name: tests
        working-directory: ./frontend/bike-data-app
        run: |
          yarn build
          yarn test